### ISSUE TITLE
Does not compiled

### ISSUE THREAD

**Issue by caecos** [dirkleas/DLwigglz#2] opened 2018-05-12 22:40 UTC
After been compiled. nothing happen in VCVRack...

**Comment by dirkleas** [comment] 2018-05-12 22:44
which platform/OS are you using? did you have any compilation errors? did your development VCV Rack instance run as expected?

**Comment by caecos** [comment] 2018-05-12 23:04
Running Windows 10 Pro and I get no error…when I try to open it Nothing happens…

Regards,

Marc D. Demers, Ph.D.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Saturday, May 12, 2018 6:44:42 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


which platform/OS are you using? did you have any compilation errors? did your development VCV Rack instance run as expected?

**Comment by dirkleas** [comment] 2018-05-12 23:51
I'll test and attempt to replicate on Windows10 and get back to you ASAP -- I'm developing on macos by default. thanks, Marc

**Comment by dirkleas** [comment] 2018-05-13 06:28
Can you describe what happens when you add the **r4xH4x** module after you successfully compile? To use **r4xH4x**, press the `Catalog` button to create a file named `catalog.partial.json` will be generated and placed in your `plugins` folder. This file provides a partial catalog of all your installed plugin modules -- everything but `width` for your modules.

**Comment by caecos** [comment] 2018-05-13 15:42
Where is the Catalog button !?


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Sunday, May 13, 2018 2:28:05 AM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


Can you describe what happens when you add the r4xH4x module after you successfully compile? To use r4xH4x, press the Catalog button to create a file named catalog.partial.json will be generated and placed in your plugins folder. This file provides a partial catalog of all your installed plugin modules -- everything but width for your modules.

**Comment by dirkleas** [comment] 2018-05-13 20:25
if you install this project plugin module `DLwigglz r4xH4x` and add it to your patch, you'll see [this](https://user-images.githubusercontent.com/52076/39953295-911a6a5c-5576-11e8-965b-0f1743ff2cbd.png)

**Comment by caecos** [comment] 2018-05-13 23:36
The module didn’t show up…Nothing happen…there is Something broken somewhere but my expertise in coding is not enough to find the bug…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Sunday, May 13, 2018 4:25:38 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


if you install this project plugin module DLwigglz r4xH4x and add it to your patch, you'll see this<https://user-images.githubusercontent.com/52076/39953295-911a6a5c-5576-11e8-965b-0f1743ff2cbd.png>

**Comment by DomiKamu** [comment] 2018-05-14 15:57
Hi, I confirm the issue opened by caecos (Marc) I'm using Windows 7, but absolutely nothing are displayed (no GUI, no button)...

**Comment by dirkleas** [comment] 2018-05-14 17:41
does anything show up in the rack log/console?

**Comment by dirkleas** [comment] 2018-05-14 18:59
just build fresh VCV Rack (v0.6) on a Windows 10 vm, the this project's plugin, and it appears and functions as expected. 

when you built your VCV Rack from source, did you switch from master (default after clone) to 0.6 via `git checkout v0.6` before `make dep` and `make`? I installed msys2 fresh today as well

**Comment by caecos** [comment] 2018-05-14 19:53
Can you Dropbox the binairies ?

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Monday, May 14, 2018 2:59:29 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


just build fresh VCV Rack (v0.6) on a Windows 10 vm and it appears and functions as expected.

when you built your VCV Rack from source, did you switch from master (default after clone) to 0.6 via git checkout v0.6 before make dep and make? I installed msys2 fresh today as well

**Comment by caecos** [comment] 2018-05-14 19:59
Does not works for me… ☹

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Monday, May 14, 2018 2:59:29 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


just build fresh VCV Rack (v0.6) on a Windows 10 vm and it appears and functions as expected.

when you built your VCV Rack from source, did you switch from master (default after clone) to 0.6 via git checkout v0.6 before make dep and make? I installed msys2 fresh today as well

**Comment by dirkleas** [comment] 2018-05-14 20:25
published preliminary binaries for MacOS and Windows (both 64-bit) here, let me know how it goes

**Comment by caecos** [comment] 2018-05-14 20:36
Save as my compiles version…show up in the navigator but does show up in rack once clicking on the module…


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Monday, May 14, 2018 4:25:43 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


published preliminary binaries for MacOS and Windows (both 64-bit) here, let me know how it goes

**Comment by caecos** [comment] 2018-05-15 01:40
The module does not appear in Rack

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dirk Leas <notifications@github.com>
Envoyé : Monday, May 14, 2018 4:25:43 PM
À : dirkleas/DLwigglz
Cc : caecos; Author
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


published preliminary binaries for MacOS and Windows (both 64-bit) here, let me know how it goes

**Comment by dirkleas** [comment] 2018-05-15 01:45
@caecos, are you running the 64-bit version of VCV Rack? @DomiKamu, did the binary work for you?

Sorry, I'm unable to replicate your particular situation, @caecos  -- perhaps we could troubleshoot further offline? Otherwise, I'll be posting some walkthrough videos in the near term that might reflect what we're doing differently.

**Comment by DomiKamu** [comment] 2018-05-15 04:52
I've also tried the binary provided (from "release"), but doesn't work too: in both cases, the module is correctly listed from module browser, but nothing appears in rack when I bring it.

Also, I precise VCV Rack works only on 64-bit Windows (32-bit isn't supported).

**Comment by dirkleas** [comment] 2018-05-15 14:34
progress -- I've replicated, now troubleshooting. thanks for your help, I'll post a new release once issue is resolved

**Comment by dirkleas** [comment] 2018-05-15 15:43
found it! the problem was caused by the way my SVG was getting saved by Affinity Design (AD) by default -- here's what Rack likes: `<svg width="90px" height="380px" ...`, and AD was setting geometry to `100%` and using another SVG construct for actual height/width. I fixed with the latest commit, and updated the release. let me know if this resolves your display issue

**Comment by DomiKamu** [comment] 2018-05-15 16:51
Thanks Dirk (I'm speaking for Marc - if you permit), of course I've took a look about... source code (instead of SVG because I was able to open it from Inkscape 0.92 without issue). Now it's better, but they're no displayed text around buttons, so be sure all texts (and objects) are converted to path (or something like) in your SVGs files (see zoomed screen capture for comparison). ;)
![sans titre-1](https://user-images.githubusercontent.com/24851960/40071358-d2f2947a-5870-11e8-97e2-b7ab921fef96.png)

**Comment by DomiKamu** [comment] 2018-05-15 16:58
By doing by myself (texts to paths) from Inkscape, all texts are - unfortunately - badly placed into GUI...
![sans titre-1](https://user-images.githubusercontent.com/24851960/40071728-ece9a200-5871-11e8-91a9-37a7a9160262.png)

**Comment by dirkleas** [comment] 2018-05-15 19:10
thanks for the feedback -- it definitely appears to be a configuration/export profile settings issue with my Affinity Designer. I've committed a new .svg file generated with different settings, can you take a look? you don't need to rebuild, just download the res/R4xH4x.svg file and replace the one in your plugins folder (fingers crossed ;-)) I miss inkscape, but it's fidgety on a mac

**Comment by DomiKamu** [comment] 2018-05-15 20:11
![sans titre-1](https://user-images.githubusercontent.com/24851960/40081031-1d1857ee-588d-11e8-9adc-b7ad688437a7.png)
You're welcome! and I confirm now the GUI is working. ;)

**Comment by dirkleas** [comment] 2018-05-15 20:18
outstanding! thanks again for all the help! enjoy!

you might also like my rack [fork](https://github.com/dirkleas/Rack) which generates a full catalog, or I'm very near rolling out [rackcloud](https://github.com/dirkleas/rackcloud), a cloud service that will work with [rackcli](https://github.com/dirkleas/rackcli) to provide width data for the partial catalog generated by r4xHrx -- keep an eye out here. also making some walkthru vids to ease onboarding

**Comment by dirkleas** [comment] 2018-05-15 20:26
here are the Affinity Designer 1.6.0 for macOS export profile settings compatible with VCV Rack 0.6.0 (thanks, LLR!)

![affinitydesignerexport](https://user-images.githubusercontent.com/52076/40081649-95a1affc-585c-11e8-9a37-ed3cb251ceb7.png)

**Closed as completed by dirkleas** 2018-05-15 20:26 UTC
Labels: bug, help wanted

**Comment by caecos** [comment] 2018-05-15 20:58
Here also, the GUI is appearing now…many thanks

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : DomiKamu <notifications@github.com>
Envoyé : Tuesday, May 15, 2018 4:11:20 PM
À : dirkleas/DLwigglz
Cc : caecos; Mention
Objet : Re: [dirkleas/DLwigglz] Does not compiled (#2)


You're welcome! and I confirm now the GUI is working. ;)
